<?php

declare (strict_types=1);
/*
 * This file is part of the Predis package.
 *
 * (c) 2009-2020 Daniele Alessandri
 * (c) 2021-2026 Till Krüss
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
namespace Predis;

use Exception;
use Predis\Connection\Node_Connection_Interface;
/**
 * Base exception class for network-related errors.
 */
abstract class Communication_Exception extends Predis_Exception
{
    private $connection;
    /**
     * @param NodeConnectionInterface $connection     Connection that generated the exception.
     * @param string                  $message        Error message.
     * @param int                     $code           Error code.
     * @param Exception|null          $innerException Inner exception for wrapping the original error.
     */
    public function __construct(Node_Connection_Interface $connection, $message = '', $code = 0, ?Exception $inner_exception = null)
    {
        parent::__construct(is_null($message) ? '' : $message, is_null($code) ? 0 : $code, $inner_exception);
        $this->connection = $connection;
    }
    /**
     * Gets the connection that generated the exception.
     *
     * @return NodeConnectionInterface
     */
    public function get_connection()
    {
        return $this->connection;
    }
    /**
     * Indicates if the receiver should reset the underlying connection.
     *
     * @return bool
     */
    public function should_reset_connection()
    {
        return true;
    }
    /**
     * Helper method to handle exceptions generated by a connection object.
     *
     * @param CommunicationException $exception Exception.
     *
     * @throws CommunicationException
     */
    public static function handle(Communication_Exception $exception): void
    {
        if ($exception->should_reset_connection()) {
            $connection = $exception->get_connection();
            if ($connection->is_connected()) {
                $connection->disconnect();
            }
        }
        throw $exception;
    }
}