<?php

declare (strict_types=1);
/*
 * This file is part of the Predis package.
 *
 * (c) 2009-2020 Daniele Alessandri
 * (c) 2021-2026 Till Krüss
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
namespace Predis\Monitor;

use Iterator;
use Predis\Client_Interface;
use Predis\Connection\Cluster\Cluster_Interface;
use Predis\Not_Supported_Exception;
use Return_Type_Will_Change;
/**
 * Redis MONITOR consumer.
 */
class Consumer implements Iterator
{
    private $client;
    private $valid;
    private $position;
    /**
     * @param ClientInterface $client Client instance used by the consumer.
     */
    public function __construct(Client_Interface $client)
    {
        $this->assert_client($client);
        $this->client = $client;
        $this->start();
    }
    /**
     * Automatically stops the consumer when the garbage collector kicks in.
     */
    public function __destruct()
    {
        $this->stop();
    }
    /**
     * Checks if the passed client instance satisfies the required conditions
     * needed to initialize a monitor consumer.
     *
     * @param ClientInterface $client Client instance used by the consumer.
     *
     * @throws NotSupportedException
     */
    private function assert_client(Client_Interface $client): void
    {
        if ($client->get_connection() instanceof Cluster_Interface) {
            throw new Not_Supported_Exception('Cannot initialize a monitor consumer over cluster connections.');
        }
        if (!$client->get_command_factory()->supports('MONITOR')) {
            throw new Not_Supported_Exception("'MONITOR' is not supported by the current command factory.");
        }
    }
    /**
     * Initializes the consumer and sends the MONITOR command to the server.
     */
    protected function start()
    {
        $this->client->execute_command($this->client->create_command('MONITOR'));
        $this->valid = true;
    }
    /**
     * Stops the consumer. Internally this is done by disconnecting from server
     * since there is no way to terminate the stream initialized by MONITOR.
     */
    public function stop(): void
    {
        $this->client->disconnect();
        $this->valid = false;
    }
    #[Return_Type_Will_Change]
    public function rewind(): void
    {
        // NOOP
    }
    /**
     * Returns the last message payload retrieved from the server.
     *
     * @return object
     */
    #[Return_Type_Will_Change]
    public function current()
    {
        return $this->get_value();
    }
    /**
     * @return int|null
     */
    #[Return_Type_Will_Change]
    public function key()
    {
        return $this->position;
    }
    #[Return_Type_Will_Change]
    public function next(): void
    {
        ++$this->position;
    }
    /**
     * Checks if the the consumer is still in a valid state to continue.
     *
     * @return bool
     */
    #[Return_Type_Will_Change]
    public function valid()
    {
        return $this->valid;
    }
    /**
     * Waits for a new message from the server generated by MONITOR and returns
     * it when available.
     *
     * @return object
     */
    private function get_value()
    {
        $database = 0;
        $client = null;
        $event = $this->client->get_connection()->read();
        $callback = static function ($matches) use (&$database, &$client): string {
            if (2 === $count = count($matches)) {
                // Redis <= 2.4
                $database = (int) $matches[1];
            }
            if (4 === $count) {
                // Redis >= 2.6
                $database = (int) $matches[2];
                $client = $matches[3];
            }
            return ' ';
        };
        $event = preg_replace_callback('/ \(db (\d+)\) | \[(\d+) (.*?)\] /', $callback, $event, 1);
        @[$timestamp, $command, $arguments] = explode(' ', $event, 3);
        return (object) ['timestamp' => (float) $timestamp, 'database' => $database, 'client' => $client, 'command' => substr($command, 1, -1), 'arguments' => $arguments];
    }
}